# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: local
    hooks:
    -   id: change-refs-to-synergy-repo
        name: change-refs-to-synergy-repo
        entry: .github/workflows/scripts/change_refs_to_synergy_repo.sh
        language: script
        pass_filenames: false
