services:
  fair_eva:
    labels:
      traefik.http.routers.web.tls: true
      traefik.http.routers.web.tls.certResolver: letsEncrypt
      traefik.http.routers.web.entrypoints: websecure
      traefik.http.routers.api.tls: true
      traefik.http.routers.api.tls.certResolver: letsEncrypt
      traefik.http.routers.api.entrypoints: websecure

  reverse-proxy:
    command:
      # for some reason extending does *not* merge command, so I'm pasting these here as well
      - "--entrypoints.web.address=:80"
      - "--providers.docker"

      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsEncrypt.acme.storage=/etc/traefik/mounted/acme.json"
      - "--certificatesresolvers.letsEncrypt.acme.email=${LETSENCRYPT_EMAIL}"
      - "--certificatesresolvers.letsEncrypt.acme.tlschallenge=true"
      - "--accesslog=true"
      - "--accesslog.filePath=/var/log/traefik/access.log"
    volumes:
      - ./traefik/:/etc/traefik/mounted/
      - ./traefik/log:/var/log/traefik/
    ports:
      - "443:443"

